---
# handlers file for deploy_wordpress_db

- name: restart MySQL
  systemd:
    name: mysql
    state: restarted
  become: yes

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
  become: yes
